/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Model.WeightDims;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gasto
 */
public class FormProductsModels extends javax.swing.JFrame {

    DefaultTableModel dtmWeightDims;
    String nombreArchivo = " ";
    String encabezados = " ";
    String salida = " ";
    private boolean testUpdate = false;
    
    ImageIcon iconDelete = new ImageIcon("images\\delete.png");
    ImageIcon iconAdd = new ImageIcon("images\\add.png");
    
    ListSelectionModel listSelectionModel = null;
    
    public FormProductsModels() {        
        initComponents();        
        jButtonAdd.setIcon(iconAdd);
        jButtonDelete.setIcon(iconDelete);
        jButtonAdd.requestFocus();
        
        dtmWeightDims = new DefaultTableModel();
        /*{
            @Override
               public boolean isCellEditable(int fila, int columna) {
                  return false; //Con esto conseguimos que la tabla no se pueda editar
               }
        };
        */
        
        jTProductsModels.setModel(dtmWeightDims);
        
        dtmWeightDims.addColumn("Model");
        dtmWeightDims.addColumn("L");
        dtmWeightDims.addColumn("W");
        dtmWeightDims.addColumn("H");
        dtmWeightDims.addColumn("Weight");
                   
        visualizarProductsModels();

        listSelectionModel = jTProductsModels.getSelectionModel();        
        listSelectionModel.addListSelectionListener((ListSelectionEvent e) -> {            
            if(e.getValueIsAdjusting()){
                int fila = listSelectionModel.getMinSelectionIndex();
                areaTexto.append("--> updated row " + listSelectionModel.getMinSelectionIndex()+
                        "|"+dtmWeightDims.getValueAt(fila, 0)+"|"+dtmWeightDims.getValueAt(fila, 1)+
                        "\n");
                testUpdate = true;
            }            
        });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTProductsModels = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        jButtonDelete = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextModelo = new javax.swing.JTextField();
        jTextL = new javax.swing.JTextField();
        jTextW = new javax.swing.JTextField();
        jTextH = new javax.swing.JTextField();
        jTextWeight = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProductsModels");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTProductsModels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTProductsModels);

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane2.setViewportView(areaTexto);

        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Model");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("L");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("W");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("H");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Weight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonDelete)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextW, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(jTextWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(58, 58, 58)
                                    .addComponent(jButtonAdd))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        dtmWeightDims.addRow(new Object[]{jTextModelo.getText(), jTextL.getText(), 
            jTextW.getText(),jTextH.getText(),jTextWeight.getText()});
        
        areaTexto.append("--> ProductsModels added\n");
        jTextModelo.setText("");
        jTextL.setText("");
        jTextW.setText("");
        jTextH.setText("");
        jTextWeight.setText("");
        testUpdate = true;
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int fila = jTProductsModels.getSelectedRow();
        if (fila >= 0) {
            int option = JOptionPane.showConfirmDialog(null,
                    "Are you sure you want to Delete? \n"+"Model "+
                            dtmWeightDims.getValueAt(fila, 0)
                    , "Delete confirmation", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                dtmWeightDims.removeRow(fila);
                areaTexto.append("--> deleted row\n");
                testUpdate = true;
            }
        } else {
            areaTexto.append("--> Please select a row to delete\n");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(0); // Desactiva el boton cerrar 
        if (testUpdate){
            grabarModelsCSV();
            testUpdate=false;
        }
        this.setVisible(false); 
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProductsModels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProductsModels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProductsModels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProductsModels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProductsModels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTProductsModels;
    private javax.swing.JTextField jTextH;
    private javax.swing.JTextField jTextL;
    private javax.swing.JTextField jTextModelo;
    private javax.swing.JTextField jTextW;
    private javax.swing.JTextField jTextWeight;
    // End of variables declaration//GEN-END:variables

    private void visualizarProductsModels() {
        areaTexto.append("********** ProductsModels.visualizarProductsModels **********\n");
        nombreArchivo = "WeightDimsCSV.csv";
        try ( BufferedReader fileEntrada = new BufferedReader(new FileReader(nombreArchivo))) {
            //Ignorar encabezados
            encabezados = fileEntrada.readLine();
            while ((salida = fileEntrada.readLine()) != null) {

                String[] celdas = salida.split(";");
                
                WeightDims weightDims = new WeightDims(celdas[0], celdas[1], 
                        celdas[2], celdas[3], celdas[4]);

                //Construye TableModel
                Object[] fila = new Object[5];
                fila[0]= weightDims.getModelo();
                fila[1]= weightDims.getL();
                fila[2]= weightDims.getW();
                fila[3]= weightDims.getH();
                fila[4]= weightDims.getWeight();
                dtmWeightDims.addRow(fila);
            }
            fileEntrada.close();            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "visualizarProductsModels().fileEntrada." + e.getMessage());
        }
        jTProductsModels.updateUI();
        jScrollPane1.setViewportView(jTProductsModels);
    }

    private void grabarModelsCSV() {
        areaTexto.append("\n********** openFileProductsModels() **********\n");
        
        FileWriter fileCSV = null;
        BufferedWriter bufferWriteCSV = null;       

        nombreArchivo = "WeightDimsCSV.csv";
        String salida = "";

        try {
            fileCSV = new FileWriter(nombreArchivo);
            bufferWriteCSV = new BufferedWriter(fileCSV);
            areaTexto.append("fileProductsModels[" + nombreArchivo + "]\n");            
            
            int filas = dtmWeightDims.getRowCount();
            int columnas = dtmWeightDims.getColumnCount();
            for(int i=0; i<filas; i++) {
                salida = dtmWeightDims.getValueAt(i, 0).toString();
                for(int j=1; j<columnas; j++){
                    salida+=";"+dtmWeightDims.getValueAt(i, j).toString();
                }
                areaTexto.append(salida+"\n"); 
                bufferWriteCSV.write(salida+"\n");
            }  
            bufferWriteCSV.close();
            areaTexto.append("--> update Products Models\n"); 
            JOptionPane.showMessageDialog(null, "End Process Update Products Models.");
        } catch (IOException ex) {
            areaTexto.append("Error openFileProductsModels[" + nombreArchivo + "]\n" + ex.getMessage() + "\n");
        }
    }   

    public boolean isTestUpdate() {
        return testUpdate;
    }
}
